Initial Server Code
BobaTalks/bobabot pull request #1
Opened 2023-03-17 17:08 UTC by a-camarillo

## Description
#### What is the purpose of your change?
- Adds initial web server code. This includes routing for /tags and functionality for interacting with the database.

#### What areas of the application does this change impact? (changes API, folder structure, etc)
- Server/API

#### What features/fixes are deferred/not handled in this PR?
- N/A

## Checklist
- [ ] Adds unit tests
- [ ] Has a work item linked to the PR

2023-03-21 16:15 UTC, jwu910 requested changes

2023-03-21 16:15 UTC, jwu910 commented on server/db.py
> +    return ("Delete Successful",200)
do we want to also include try except blocks here? What are some edge cases for failure/error?

2023-03-21 16:15 UTC, jwu910 commented on server/routes.py
> +conn = db.init_db()
Should we use a less ambiguous abbreviation? could we just use `database` or something explicit?

2023-03-21 16:15 UTC, jwu910 commented on server/routes.py
> +        return res
instead of `res` as the return variable, can we call this something like `tag` to be more indicative of what the entity actually is?

2023-03-21 16:15 UTC, jwu910 commented on server/routes.py
> +def tags_by_id(tag_id):
If this returns a single tag, we should probably name this as singular `tag_by_id`

2023-03-21 16:15 UTC, jwu910 commented on server/routes.py
> +        return res
same comment above about the return variable name. do we need to return the list of new tags after a successful delete, or a message + status, etc?

2023-03-21 16:15 UTC, jwu910 commented on server/routes.py
do we need to try-except block the actions in this file?

2023-03-21 18:18 UTC, a-camarillo commented on server/db.py
> +    return ("Delete Successful",200)
We can likely add try except blocks for consistency, however, those blocks are meant for handling errors. In the case where the function checks if the string is null, the mongo driver does not return an error so I'm not sure if the try-except behavior would be the same. 

Alternatively, we can implement an `Error` class and raise a `NullError` to keep the consistency of try-except across all functions

2023-03-22 01:12 UTC, a-camarillo commented
Cleaned up some of the naming. Currently all error handling is done in `database.py` and each function returns a tuple. In Flask, the routing functions can return a tuple that follows the structure `(response, status)`. This is how the routes are currently handling response and status code, it kind of just depends if we want to handle errors and status codes.

I think the current approach keeps the routing code cleaner and more readable.

2023-03-22 07:16 UTC, jwu910 approved these changes

2023-03-22 07:16 UTC, merged